name: CI

# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build:

    # Runs the job on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      working-directory: my-chatbot
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: my-chatbot
      run: npm install

    - name: Run tests
      working-directory: my-chatbot
      run: npm test

    - name: Build project
      working-directory: my-chatbot
      run: npm run build

    
